#!/bin/bash
echo "🚀 Testing MIR-UR Integration"
echo "=============================="
echo ""
echo "Your systems are running:"
echo "✅ UR Robot: 192.168.1.6 - Connected"
echo "✅ MIR Base: 118.138.107.60 - Connected (MiR_R1069)"
echo ""
echo "🎯 TEST WORKFLOW:"
echo ""
echo "1. Use MIR website to send MIR to a location"
echo "2. When MIR reaches target, run these commands:"
echo ""
echo "   # For pickup location:"
echo "   echo 'add pickup 0.1 true' >> control/robot_commands.txt"
echo ""
echo "   # For dropoff locations:"
echo "   echo 'add dropoff1 0.1 true' >> control/robot_commands.txt"
echo "   echo 'add dropoff2 0.1 true' >> control/robot_commands.txt"
echo "   echo 'add dropoff3_safe 0.1 true' >> control/robot_commands.txt"
echo "   echo 'add dropoff4_safe 0.1 true' >> control/robot_commands.txt"
echo ""
echo "   # Or use the interactive system:"
echo "   python3 quick_mir_integration.py"
echo ""
echo "🔍 MONITOR SYSTEM:"
echo "   watch -n 1 'cat control/robot_response.txt | tail -10'"
echo "   tail -f control/robot_response.txt"
echo ""
echo "✨ Ready for testing! 🎯"